const words = [
["Bila shaka", "course"],
["Dutu", "substance"],
["Kudanganywa", "to be cheated"],
["Machapisho", "locate"],
["Ondoa", "subtract"],
["Onyesha", "show"],
["Spell", "spell"],
["a", "a"],
["adui", "enemy"],
["aina", "form"],
["aina", "kind"],
["aina", "type"],
["ajabu", "strange"],
["ajabu", "wonder"],
["akaanguka", "fell"],
["akaenda", "went"],
["akaonekana", "the"],
["akili", "mind"],
["alama", "mark"],
["alama", "score"],
["aliandika", "wrote"],
["alianza", "began"],
["alichukua", "took"],
["alifanya", "did"],
["alifanya", "made"],
["aliiambia", "told"],
["alijua", "knew"],
["alikuja", "came"],
["alikuwa", "had"],
["alimtuma", "sent"],
["alisema", "said"],
["alisimama", "stood"],
["alitoa", "gave"],
["aliyezaliwa", "born"],
["alizungumza", "spoke"],
["ama", "either"],
["ambao", "who"],
["ambao", "whose"],
["ambapo", "where"],
["ambayo", "which"],
["ameketi", "sat"],
["amini", "believe"],
["an", "an"],
["anga", "sky"],
["angalau", "least"],
["ardhi", "ground"],
["ardhi", "land"],
["asili", "natural"],
["asili", "nature"],
["askari", "soldier"],
["asubuhi", "morning"],
["atakuwa", "shall"],
["athari", "effect"],
["au", "or"],
["awali", "original"],
["aya", "paragraph"],
["baada ya", "after"],
["baada", "post"],
["baadhi ya", "certain"],
["baadhi", "some"],
["baba", "dad"],
["baba", "father"],
["badala", "rather"],
["badala", "stead"],
["bado", "still"],
["bado", "yet"],
["bahari", "ocean"],
["bahari", "sea"],
["bandari", "port"],
["bar ya", "bar"],
["bara", "continent"],
["barabara", "road"],
["barafu", "ice"],
["baridi", "cold"],
["baridi", "cool"],
["barua", "letter"],
["basi", "let"],
["bat kwa", "bat"],
["bata", "duck"],
["bega", "shoulder"],
["bendi", "band"],
["benki", "bank"],
["biashara", "trade"],
["bidhaa", "product"],
["binadamu", "human"],
["binafsi", "self"],
["bluu", "blue"],
["bodi", "board"],
["bonde", "valley"],
["bora", "best"],
["bora", "better"],
["bunduki", "gun"],
["bure", "free"],
["bustani", "garden"],
["busy", "busy"],
["bwana", "master"],
["cent", "cent"],
["chache", "few"],
["chakula", "food"],
["chama", "party"],
["changanya", "to mix or confuse"],
["changanyikiwa", "to be mixed or confused"],
["chati", "chart"],
["chembe", "atom"],
["chemchemi", "spring"],
["chini ya", "less"],
["chini ya", "under"],
["chini", "bottom"],
["chini", "down"],
["chini", "low"],
["chochote", "nothing"],
["chombo", "instrument"],
["chombo", "organ"],
["chombo", "tool"],
["chuma", "iron"],
["chuma", "metal"],
["chuma", "steel"],
["chumba", "room"],
["chumvi", "salt"],
["chupa", "pound"],
["consonant", "consonant"],
["cover", "cover"],
["dada", "sister"],
["daima", "always"],
["dakika", "minute"],
["daktari", "doctor"],
["damu", "blood"],
["darasa", "class"],
["decimal", "decimal"],
["dhahabu", "gold"],
["dhidi ya", "against"],
["dirisha", "window"],
["doa", "spot"],
["dola", "dollar"],
["duka", "shop"],
["dunia", "earth"],
["dunia", "world"],
["elfu", "thousand"],
["eneo", "area"],
["faini", "fine"],
["familia", "family"],
["farasi", "horse"],
["fedha", "money"],
["fedha", "silver"],
["fimbo", "stick"],
["fit", "fit"],
["full", "full"],
["furaha", "fun"],
["furaha", "glad"],
["furaha", "happy"],
["furaha", "joy"],
["ganda", "shell"],
["gani", "does"],
["gari", "car"],
["gari", "drive"],
["gesi", "gas"],
["ghafla", "sudden"],
["gharama", "cost"],
["giza", "dark"],
["gorofa", "flat"],
["got", "got"],
["gumzo", "chord"],
["gurudumu", "wheel"],
["habari", "heard"],
["habari", "mass"],
["hadithi", "story"],
["haijalishi", "It doesn’t matter"],
["haja", "need"],
["haki", "fair"],
["haki", "right"],
["hakuna", "no"],
["hali ya hewa", "weather"],
["hali", "condition"],
["hali", "state"],
["halisi", "exact"],
["halisi", "real"],
["hapa", "here"],
["haraka", "fast"],
["haraka", "hurry"],
["haraka", "quick"],
["harufu", "smell"],
["hasa", "especially"],
["hasa", "particular"],
["hasira", "anger"],
["hata", "even"],
["hatari", "danger"],
["hatua", "step"],
["hawakupata", "caught"],
["haya", "these"],
["hewa", "air"],
["high", "high"],
["hii", "this"],
["historia", "history"],
["hit", "hit"],
["hivi karibuni", "soon"],
["hivyo", "so"],
["hivyo", "thus"],
["hofu", "afraid"],
["hofu", "fear"],
["hoja", "move"],
["hotuba", "speech"],
["huduma", "care"],
["huko", "there"],
["hukumu", "sentence"],
["hutegemea", "depend"],
["idadi ya", "populate"],
["ijayo", "next"],
["ila", "except"],
["ilani", "notice"],
["ili", "order"],
["ilikua", "grew"],
["iliyopita", "ago"],
["imeandikwa", "written"],
["imekuwa", "been"],
["ina", "has"],
["inaweza", "could"],
["inaweza", "may"],
["inchi", "inch"],
["ingawa", "though"],
["ingekuwa", "would"],
["injini", "engine"],
["ishara", "sign"],
["ishara", "symbol"],
["ishirini", "twenty"],
["itaonekana", "appear"],
["iwezekanavyo", "possible"],
["jambo", "matter"],
["jangwa", "desert"],
["jibu", "answer"],
["jibu", "reply"],
["jicho", "eye"],
["jina", "name"],
["jinsi", "how"],
["jioni", "evening"],
["jirani", "neighbor"],
["jiwe", "stone"],
["joto", "heat"],
["joto", "temperature"],
["joto", "warm"],
["jozi", "pair"],
["jua", "sun"],
["jumla", "total"],
["juu ya", "on"],
["juu ya", "over"],
["juu", "above"],
["juu", "top"],
["kabisa", "quite"],
["kabla ya", "before"],
["kadhaa", "several"],
["kadi", "card"],
["kahawia", "brown"],
["kama", "as"],
["kama", "if"],
["kama", "like"],
["kama", "such"],
["kama", "whether"],
["kamba", "rope"],
["kamba", "string"],
["kambi", "camp"],
["kamili", "complete"],
["kampuni", "company"],
["kamusi", "dictionary"],
["kamwe", "never"],
["kanda", "region"],
["kanzu", "coat"],
["karatasi", "paper"],
["karatasi", "sheet"],
["karibu", "close"],
["karibu", "near"],
["karne ya", "century"],
["kasi", "speed"],
["kaskazini", "north"],
["kata", "cut"],
["kati ya", "among"],
["kati ya", "between"],
["kati yake", "flow"],
["katika", "at"],
["katika", "in"],
["katikati", "middle"],
["kavu", "dry"],
["kawaida", "common"],
["kawaida", "usual"],
["kazi", "job"],
["kazi", "operate"],
["kazi", "work"],
["kelele", "noise"],
["kelele", "shout"],
["kengele", "bell"],
["kesi", "case"],
["kiasi", "much"],
["kiatu", "shoe"],
["kichwa", "head"],
["kidogo", "bit"],
["kidogo", "little"],
["kidole", "finger"],
["kifaranga", "chick"],
["kifo", "death"],
["kiini", "cell"],
["kijani", "green"],
["kijiji", "village"],
["kijivu", "gray"],
["kila", "all"],
["kila", "each"],
["kila", "every"],
["kilima", "hill"],
["kilio", "cry"],
["kimya", "silent"],
["kina", "deep"],
["kinachowezekana", "probable"],
["kinyume", "opposite"],
["kinywa", "mouth"],
["kioevu", "liquid"],
["kioo", "glass"],
["kipande", "piece"],
["kipengele", "element"],
["kipindi", "period"],
["kisasa", "modern"],
["kisha", "then"],
["kisichowezekana", "impossible thing"],
["kisiwa", "island"],
["kitabu", "book"],
["kitanda", "bed"],
["kitengo", "unit"],
["kitenzi", "verb"],
["kiti cha", "seat"],
["kiti", "chair"],
["kitu", "object"],
["kitu", "thing"],
["kituo cha", "center"],
["kituo cha", "station"],
["kofia", "hat"],
["koloni", "colony"],
["kona", "corner"],
["ku pitia", "to go through"],
["kuabudu", "to worship"],
["kuacha", "&nbsp;»to stop, leave&nbsp;»"],
["kuacha", "drop"],
["kuacha", "stop"],
["kuacha", "to stop, leave something, allow someone to do something"],
["kuachana", "to divorce"],
["kuadhibu", "to punish"],
["kuagana", "to say goodbye to each other"],
["kuagiza", "to order"],
["kuahidi", "to promise"],
["kuaibisha", "to shame"],
["kuajiri", "to employ"],
["kualika", "to invite"],
["kuambia", "to tell"],
["kuamini", "to believe"],
["kuamka", "to wake up"],
["kuamrisha", "command someone"],
["kuamsha", "to wake someone"],
["kuamua", "decide"],
["kuamua", "determine"],
["kuamua", "to decide"],
["kuandaa", "prepare"],
["kuandaa", "to prepare"],
["kuandika", "to write"],
["kuandika", "write"],
["kuandikisha", "to register"],
["kuangalia", "check"],
["kuangalia", "look"],
["kuangalia", "to look at"],
["kuangalia", "watch"],
["kuanguka", "fall"],
["kuanguka", "to fall"],
["kuanza", "begin"],
["kuanza", "start"],
["kuanza", "to start"],
["kuanzisha", "to start something"],
["kuazima", "to borrow things"],
["kuazimisha", "lend things"],
["kubadili", "to change"],
["kubadilisha", "to change"],
["kubahatisha", "be lucky"],
["kubali", "&nbsp;»agree, accept&nbsp;»"],
["kubandua", " to chop, to break, to chip"],
["kubeba", "bear"],
["kubeba", "carry"],
["kubeba", "to carry"],
["kubishana", "to argue"],
["kuboresha", "to improve"],
["kubuni", "design"],
["kubuni", "to launch, start, arrange"],
["kuburudika", "to enjoy"],
["kuburudisha", "to entertain"],
["kubwa", "big"],
["kubwa", "great"],
["kubwa", "huge"],
["kubwa", "large"],
["kubwa", "loud"],
["kuchagua", "choose"],
["kuchagua", "select"],
["kuchagua", "to choose"],
["kuchagulisha", "make choose"],
["kuchanganya", "mix"],
["kuchanganya", "to confuse"],
["kuchangia", "to contribute"],
["kuchefua", "to be sick (angry)"],
["kucheka", "laugh"],
["kucheka", "to laugh"],
["kuchemsha", "to boil"],
["kucheza", "play"],
["kucheza", "to play"],
["kuchezesha", "make someone play"],
["kuchochea", "excite"],
["kuchoka", "to be tired"],
["kuchoma sindano", "Give injection"],
["kuchoma", "burn"],
["kuchoma", "to burn"],
["kuchosha", "&nbsp;»to make tired, to bore&nbsp;»"],
["kuchukia", "to hate"],
["kuchukua", "pick"],
["kuchukua", "take"],
["kuchukua", "to carry, take"],
["kuchukulisha", "make someone take"],
["kuchuma", "to harvest / to pick"],
["kuchunguza", "observe"],
["kuchwea", "to set (sunset)"],
["kudanganya", "to cheat, lie"],
["kudhani", "to think, guess"],
["kudhibiti", "control"],
["kudhihaki", "to offend"],
["kuelekea", "toward"],
["kuelewa", "to understand"],
["kueleza", "to explain"],
["kuelezea", "describe"],
["kuenda", "to go"],
["kuendelea", "continue"],
["kuendelea", "to continue"],
["kuendeleza", "develop"],
["kuendesha", "to drive"],
["kuenea", "spread"],
["kuenye", "with, having, which"],
["kufa", "die"],
["kufa", "to die"],
["kufagia", "sweep"],
["kufahamu", "to be acquainted with"],
["kufanikiwa", "to succeed"],
["kufanya dhihaka", "make fun of"],
["kufanya kazi", "to work"],
["kufanya mzaha", "to make fun"],
["kufanya si", "don’t"],
["kufanya", "do"],
["kufanya", "make"],
["kufanya", "to do"],
["kufanyika", "to be done"],
["kufariki", "to die"],
["kufedhehesha", "to disappoint"],
["kuficha", "to hide"],
["kufika", "to arrive", " reach"],
["kufikia", "reach"],
["kufikiri kuhusu", "to think about"],
["kufikiri", "think"],
["kufikiria", "consider"],
["kufikiria", "imagine"],
["kufiwa", "to be bereaved"],
["kufua nguo", "to wash clothes"],
["kufuata", "follow"],
["kufuata", "to follow"],
["kufuatilia", "track"],
["kufufuka", "rose"],
["kufufuka", "to rise again, resurrection"],
["kufukuza", "&nbsp;»to chase, fire&nbsp;»"],
["kufulisha", "make someone wash clothes"],
["kufundisha", "teach"],
["kufundisha", "to teach"],
["kufunga", "to close"],
["kufungua", "to open"],
["kufunika", "to cover"],
["kufunua", "to uncover"],
["kufupisha", "to shorten"],
["kufurahi", "to be happy"],
["kufurahia", "to enjoy"],
["kufurahisha", "to please"],
["kufurahishwa", "be pleased"],
["kufuta vumbi", "wipe dust"],
["kugawa", "to divide"],
["kugawana", "to divide together (share)"],
["kugeuka", "to turn around"],
["kugeuza", "turn around; change something"],
["kugombana", "to fight"],
["kugonga", "&nbsp;»to hit, wreck&nbsp;»"],
["kugongana", "to hit each other"],
["kugundua", "to discover"],
["kugusa", "to touch"],
["kugusa", "touch"],
["kuhama", "to move from"],
["kuhamasika", "be motivated"],
["kuhamasisha", "to motivate"],
["kuhamia", "to move to"],
["kuhamisha", "move someone or thing"],
["kuharakisha", "hurry someone"],
["kuharibika", "not functional"],
["kuharibu", "to destroy"],
["kuhatarisha", "endanger"],
["kuhesabu", "count"],
["kuhesabu", "to count"],
["kuheshimu", "to respect"],
["kuhifadhi", "store"],
["kuhitaji", "to need"],
["kuhubiri", "to preach"],
["kuhudumia", "to serve"],
["kuhukumu", "to judge"],
["kuhusu", "about"],
["kuiba", "to steal"],
["kuimba", "melody"],
["kuimba", "sing"],
["kuimba", "to sing"],
["kuingia", "enter"],
["kuingia", "log"],
["kuingizwa", "slip"],
["kuinua", "lift"],
["kuinua", "to lift up"],
["kuisha", "to be finished"],
["kuishi", "live"],
["kuishi", "settle"],
["kuitika", "to respond"],
["kuitikia", "to respond"],
["kuja", "come"],
["kuja", "to come"],
["kujadili", "discuss"],
["kujadili", "to discuss"],
["kujali", "&nbsp;»to care, to heed, to respect&nbsp;»"],
["kujali", "to care"],
["kujaribu", "to try"],
["kujaribu", "try"],
["kujaza", "fill"],
["kujaza", "to fill"],
["kujenga", "build"],
["kujenga", "create"],
["kujenga", "to build"],
["kujibisha", "talk back"],
["kujibu", "to answer, reply"],
["kujichetua akili", "act foolishly"],
["kujifunza", "learn"],
["kujifunza", "to learn"],
["kujikwaa", "to stumble"],
["kujipodoa", "put on makeup"],
["kujisikia", "feel"],
["kujitahidi", "to make an effort"],
["kujitambulisha", "to introduce yourself"],
["kujitoa", "to give yourself"],
["kujituna", "take initiative"],
["kujiunga na", "join"],
["kujiunga", "to join yourself to something"],
["kujivuna", "to be proud"],
["kujivunia", "to be proud of someone"],
["kujua", "know"],
["kujua", "to know"],
["kujulia hali", "know how someone is doing"],
["kujulikana", "to be known"],
["kujulisha", "to inform"],
["kukaa", "sit"],
["kukaa", "stay"],
["kukaanga", "to fry"],
["kukabili", "to face"],
["kukabiliana na", "to face something"],
["kukagua", "to check"],
["kukamata", "catch"],
["kukamilika", "to be complete"],
["kukamilisha", "to complete"],
["kukana", "to deny"],
["kukanusha", "to deny"],
["kukaribisha", "to welcome"],
["kukasirika", "to be angry"],
["kukasirisha", "make angry"],
["kukataza", "to forbid"],
["kukatisha", "to cut someone off"],
["kukauka", "be dry"],
["kukausha", "make dry"],
["kukela", "to disturb"],
["kukemea pepo", "cast out demon"],
["kuketi", "to sit"],
["kukimbia", "run"],
["kukimbia", "to run"],
["kukimbiza", "to chase"],
["kukodi", "hire, rent (something not a house)"],
["kukohoa", "to cough"],
["kukonda", "to lose weight"],
["kukopa", "to borrow money"],
["kukopesha", "lend money"],
["kukosa", "&nbsp;»to miss, to make a mistake&nbsp;»"],
["kukosea", "make a mistake"],
["kukua", "grow"],
["kukua", "to grow up"],
["kukubali", "to agree"],
["kukubaliana na", "to agree with"],
["kukubaliana", "agree"],
["kukulia", "to grow up in a place"],
["kukumbatia", "to hug"],
["kukumbusha", "to remind"],
["kukuna", "to scratch"],
["kukusanya", "collect"],
["kukusanya", "gather"],
["kukutaa", "to refuse"],
["kukutana", "meet"],
["kukuza", "make grow up"],
["kukwama", "to be stuck"],
["kula bata", "to eat duck (expensive, wanting to enjoy, not serious)"],
["kula", "eat"],
["kula", "to eat"],
["kuladha", "to taste"],
["kulala", "to sleep"],
["kulalamika", "to complain"],
["kulaumu", "to blame"],
["kulaza", "to make someone sleep"],
["kulazimisha", "force someone"],
["kulegea", "be slack, loose (weak)"],
["kuleta", "bring"],
["kuleta", "to bring"],
["kuletwa", "brought"],
["kulewa", "to be drunk"],
["kulia", "to cry"],
["kuliko", "than"],
["kulinda", "protect"],
["kulinda", "to guard"],
["kulinga", "to show off"],
["kulinganisha", "compare"],
["kulipa", "pay"],
["kulipa", "to pay"],
["kulisha", "feed"],
["kumaanisha", "to mean"],
["kumaliza", "finish"],
["kumaliza", "to finish"],
["kumbuka", "remember"],
["kumenya", "to peel"],
["kumeza", "to swallow"],
["kumi", "ten"],
["kumiliki", "to own"],
["kumwagaa", "to pour out"],
["kumwagilia", "to water"],
["kunawa nuso", "wash face"],
["kunawisha", "to wash someone"],
["kundi", "group"],
["kunenepa", "to be fat"],
["kung’oa", "&nbsp;»to uproot, to pull&nbsp;»"],
["kunong’eza", "to whisper to someone"],
["kunong’ona", "to whisper"],
["kunuka", "to stink, smell bad"],
["kunukia", "to smell good"],
["kununua", "buy"],
["kununua", "to buy"],
["kununulisha", "make buy"],
["kununuliwa", "bought"],
["kunusa", "to smell"],
["kunyamaza", "keep quiet"],
["kunyanyua", "to lift up"],
["kunyesha", "to rain"],
["kunyooka", "be straight"],
["kunyoosha", "stretch"],
["kunyosha", "make straight"],
["kunywa", "drink"],
["kuoa", "to marry"],
["kuoga", "to bathe"],
["kuogelea", "swim"],
["kuogelea", "to swim"],
["kuogopa", "to be afraid"],
["kuoka", "to bake"],
["kuokoa", "save"],
["kuokoa", "to save"],
["kuokoka", "to be saved"],
["kuomba", "to pray, ask request"],
["kuona", "see"],
["kuondoa", "to remove"],
["kuondoka", "gone"],
["kuondoka", "leave"],
["kuondoka", "to depart"],
["kuonekana", "to seem, be seen"],
["kuongea", "to talk"],
["kuongeza", "add"],
["kuongeza", "raise"],
["kuongeza", "to add, increase"],
["kuongopa", "to lie"],
["kuongoza", "guide"],
["kuongoza", "to lead"],
["kuongoza", "to lead, to guide"],
["kuongozwa", "led"],
["kuonja", "to taste"],
["kuosha vyombo", "to wash dishes"],
["kuota", "to dream"],
["kupa", "to give (*always* used with object prefix)"],
["kupaa", "to ascend, ascension"],
["kupambana", "fight"],
["kupanda", "climb"],
["kupanda", "plant"],
["kupanda", "rise"],
["kupanga", "arrange"],
["kupanga", "to rent, to arrange, to plan, organize"],
["kupasha", "to heat up"],
["kupaswa", "&nbsp;»to be necessary, have to, must&nbsp;»"],
["kupata", "&nbsp;»to get, to find&nbsp;»"],
["kupata", "find"],
["kupata", "get"],
["kupatia", "to get for someone"],
["kupatikana", "found"],
["kupatikana", "to be available"],
["kupeleka", "to take someone to"],
["kupenda", "to like/love"],
["kupendekeza", "suggest"],
["kupendekeza", "to recommend"],
["kupendelea", "to prefer"],
["kupiga chabo", "cheat on test"],
["kupiga chafya", "to sneeze"],
["kupiga deki", "to mop"],
["kupiga domo", "gossip"],
["kupiga hatua", "take a step"],
["kupiga kengele", "ring bell"],
["kupiga kinanda", "play piano"],
["kupiga kura", "to vote"],
["kupiga magoti", "to kneel"],
["kupiga miayo", "to yawn"],
["kupiga mluzi", "whistle"],
["kupiga mswaki", "to brush teeth"],
["kupiga pasi", "to iron"],
["kupiga picha", "to take a picture"],
["kupiga porojo", "chat"],
["kupiga risasi", "shoot bullets"],
["kupiga simu", "to make a phone call"],
["kupiga sogo", "to chat"],
["kupiga", "to hit"],
["kupigia simu", "to telephone someone / to make a call to someone"],
["kupika", "to cook"],
["kupima", "measure"],
["kupita", "pass"],
["kupita", "to pass by"],
["kupitia", "through"],
["kupokea", "receive"],
["kupokea", "to receive"],
["kupona", "to get well"],
["kuponea chupuchupu", "barely escape"],
["kupotea", "to be lost"],
["kupoteza", "to lose something"],
["kupoza", "to cool off"],
["kupumzika", "to rest"],
["kupungua", "to be low"],
["kupunguza bei", "to reduce the price"],
["kupunguza", "ease"],
["kupunguza", "to reduce"],
["kurahisisha", "to simplify"],
["kurefusha", "to extend"],
["kuridhisha", "satsify someone"],
["kurudi", "to return"],
["kurudia", "repeat"],
["kurudia", "to repeat"],
["kurudisha", "to return something"],
["kuruhusu", "allow"],
["kuruhusu", "to permit/allow"],
["kuruka", "fly"],
["kuruka", "jump"],
["kuruka", "to jump"],
["kurusha", "to throw"],
["kusababbisha", "to cause to"],
["kusababisha", "lead"],
["kusababisha", "to cause"],
["kusafirisha", "transport"],
["kusafisha", "to clean"],
["kusahau", "to forget"],
["kusahaulisha", "make forget"],
["kusahihisha", "to correct"],
["kusaidia", "to help, assist"],
["kusali", "to pray"],
["kusalimia", "to greet"],
["kusalisha", "to lead a prayer"],
["kusamehe", "to forgive"],
["kusamehewa", "to be forgiven"],
["kusema", "say"],
["kusema", "speak"],
["kusema", "to say"],
["kusemesha", "make someone speak"],
["kushangaa", "to be surprised"],
["kusherehekea", "to celebrate"],
["kushiba", "to be full"],
["kushibisha", "make someone full"],
["kushikilia", "hold"],
["kushinda", "to win"],
["kushinda", "win"],
["kushindwa", "to be defeated"],
["kushinikiza", "push"],
["kushiriki", "share"],
["kushiriki", "to participate"],
["kushirikiana", "to cooperate"],
["kushirikisha", "to involve someone"],
["kushirikishana", "to share with each other"],
["kushona", "to sew"],
["kushoto", "left"],
["kushuka", "to descend"],
["kushukuru", "to thank"],
["kushusha", "make someone go down"],
["kusifu", "to praise"],
["kusifwa", "be praised"],
["kusikia aibu", "to feel shame"],
["kusikia", "hear"],
["kusikia", "to hear"],
["kusikiliza", "listen"],
["kusikiliza", "to listen"],
["kusikitika", "to be sad"],
["kusikitisha", "to cause sorrow / to sadden someone"],
["kusimama", "stand"],
["kusimama", "to stop, stand"],
["kusimamisha", "to stop (something)"],
["kusindikiza", "to escort"],
["kusini", "south"],
["kusinyaa", "to dry and get hard"],
["kusisitiza", "to emphasize"],
["kusoma", "read"],
["kusoma", "to read"],
["kusomesha", "make someone read, pay school fees"],
["kustaafu", "to retire"],
["kustahili", "to deserve"],
["kusubiri", "to wait"],
["kusubiri", "wait"],
["kusugua", "rub"],
["kusulubiwa", "be crucified"],
["kusulubu", "to crucify"],
["kusuluhisha", "to solve"],
["kusumbua", "&nbsp;»to disturb, to bother&nbsp;»"],
["kusumbuliwa", "to be disturbed, bothered"],
["kutabasamu", "to smile"],
["kutafakari", "to interpret together"],
["kutafsiri", "to translate / to interpret"],
["kutafuta", "to search for"],
["kutaka", "to want"],
["kutakia", "to wish (birthday)"],
["kutakiwa", "supposed to"],
["kutalaka", "to divorce"],
["kutaleza", "to slip"],
["kutamani", "to desire"],
["kutambua", "to recognize"],
["kutambulisha", "to introduce"],
["kutana na", "to meet with"],
["kutandika", "to make up bed, spread out"],
["kutangaza", "to announce"],
["kutania", "to joke"],
["kutanisha", "be made to meet"],
["kutarajia", "expect"],
["kutatua", "solve"],
["kutatua", "to solve"],
["kutawala", "to control"],
["kutayarisha", "to prepare"],
["kutazama", "to look at"],
["kutega", "to trip or trap"],
["kuteka", "draw"],
["kutembea", "to walk"],
["kutembea", "walk"],
["kutembelea", "to visit"],
["kutenda dhambi", "to sin"],
["kutenda", "done"],
["kutenda", "to do"],
["kutenga", "to separate, persecute"],
["kutengana", "to seperate"],
["kutengeneza", "&nbsp;»to fix, repair, make&nbsp;»"],
["kuthamini", "to value"],
["kuthibiti", "to control"],
["kuthibitisha", "prove"],
["kuthubutu", "to dare"],
["kutia moyo", "encourage"],
["kutia shaka", "to doubt"],
["kutia wasiwasi", "to worry"],
["kutia", "to put in"],
["kutibu", "treat (medically)"],
["kutimia", "fulfilled completed"],
["kutisha", "to scare"],
["kutoa", "give"],
["kutoa", "offer"],
["kutoa", "provide"],
["kutoa", "to give / to offer / to present"],
["kutofautiana", "vary"],
["kutoka", "from"],
["kutoka", "to come out, leave"],
["kutokea", "happen"],
["kutokea", "occur"],
["kutokea", "to happen"],
["kutosha", "enough"],
["kutosha", "to be enough"],
["kutua", "put something heavy down"],
["kutubu", "repent"],
["kutukana", "abuse, insult"],
["kutuma", "send"],
["kutumaini", "to hope"],
["kutumia", "spend"],
["kutumia", "to use"],
["kutumia", "use"],
["kutumika", "serve"],
["kutungikwa", "hung up, set"],
["kutunuku", "to crown someone"],
["kutunza", "to care for"],
["kutupa", "throw"],
["kuu", "grand"],
["kuu", "main"],
["kuu", "major"],
["kuua", "kill"],
["kuuliza swali", "to ask a question"],
["kuuliza", "ask"],
["kuuma", "hurt; bite"],
["kuumba", "to create"],
["kuumia", "to get hurt"],
["kuumiza", "to hurt"],
["kuumwa", "to be sick"],
["kuunda", "to assemble, put together"],
["kuunga mikono", "join hands"],
["kuunga", "to join, connect"],
["kuungana", "connect"],
["kuunguza", "to burn something"],
["kuuza", "sell"],
["kuuza", "to sell"],
["kuvaa nguo", "to put on clothes"],
["kuvaa", "wear"],
["kuvua", "to catch fish, undress"],
["kuvumilia", "to be patient"],
["kuvumisha", "to exaggerate"],
["kuvuna", "to harvest"],
["kuvunja", "broke"],
["kuvunja", "to break"],
["kuvunjika", "to be broken"],
["kuvunjwa", "to be broken by someone"],
["kuvuta", "pull"],
["kuvutia", "to attract"],
["kuvutiwa", "be attracted"],
["kuwa makini", "be careful"],
["kuwa mvumilivu", "to be patient"],
["kuwa", "be"],
["kuwaambia", "tell"],
["kuwahi", "to be on time"],
["kuwajibika", "to be responsible"],
["kuwaka", "&nbsp;»to burn", " shine&nbsp;»"],
["kuwakilisha", "represent"],
["kuwakilisha", "to represent"],
["kuwapiga", "beat"],
["kuwasha", "to turn on"],
["kuwashukuru", "thank"],
["kuwashwa", "to itch"],
["kuwasili", "arrive"],
["kuwasiliana", "to communicate"],
["kuweka", "&nbsp;»to put, place&nbsp;»"],
["kuweka", "keep"],
["kuweka", "lay"],
["kuweka", "put"],
["kuweka", "set"],
["kuwepo", "to be somewhere"],
["kuweza", "to be able to"],
["kuwinda", "hunt"],
["kuwinda", "to hunt"],
["kuzaa", "to give birth"],
["kuzalisha", "produce"],
["kuzaliwa", "to be born"],
["kuzama", "to sink"],
["kuzeesha", "make someone old"],
["kuzidisha", "multiply"],
["kuzika", "to bury"],
["kuzima", "to extinguish"],
["kuzini", "adultery"],
["kuzoa", "to gather up"],
["kuzoea", "to be used to"],
["kuzolesha", "make someone gather up"],
["kuzua", "to instigate, start something"],
["kuzuia", "block"],
["kuzuka", "to pop up suddenly"],
["kuzungumza", "to converse"],
["kwa mkweli", "be honest"],
["kwa nini", "why"],
["kwa", "for"],
["kwa", "to"],
["kwa", "with"],
["kwamba", "that"],
["kwanza", "first"],
["kweli", "true"],
["kwenda", "go"],
["labda", "perhaps"],
["laini", "soft"],
["lakini", "but"],
["lami", "pitch"],
["lazima", "must"],
["lazima", "should"],
["line", "line"],
["lita moja", "quart"],
["litasababisha", "pose"],
["lori", "truck"],
["lugha", "language"],
["maalum", "special"],
["maana", "mean"],
["maana", "meant"],
["maana", "sense"],
["maarufu", "famous"],
["mabadiliko ya", "change"],
["madai", "claim"],
["mafanikio", "success"],
["mafuta", "fat"],
["mafuta", "oil"],
["magazeti", "print"],
["magharibi", "west"],
["mahali", "place"],
["maili", "mile"],
["maisha", "life"],
["majadiliano", "talk"],
["majaribio", "experiment"],
["maji", "water"],
["majira ya baridi", "winter"],
["majira ya joto", "summer"],
["makali", "edge"],
["makosa", "wrong"],
["mali", "property"],
["malipo", "charge"],
["mama", "mother"],
["maneno", "phrase"],
["mapema", "early"],
["mapenzi", "will"],
["mapumziko", "break"],
["mara mbili", "double"],
["mara moja", "once"],
["mara nyingi", "often"],
["mara", "was"],
["marehemu", "late"],
["mashariki", "east"],
["mashine", "machine"],
["mashua", "boat"],
["maskini", "poor"],
["maslahi", "interest"],
["matokeo", "result"],
["matumaini", "hope"],
["matunda", "fruit"],
["mavazi", "dress"],
["mazao", "crop"],
["maziwa", "milk"],
["mazoezi", "practice"],
["mbali", "distant"],
["mbali", "far"],
["mbali", "off"],
["mbalimbali", "range"],
["mbao", "wood"],
["mbaya", "bad"],
["mbegu", "seed"],
["mbele", "forward"],
["mbele", "front"],
["mbele", "sight"],
["mbili", "two"],
["mbio", "race"],
["mbio", "ran"],
["mboni", "apple"],
["mbwa", "dog"],
["mchakato", "process"],
["mchanga", "sand"],
["mchezo", "game"],
["mechi", "match"],
["meli", "sail"],
["meli", "ship"],
["mengi", "lot"],
["meno", "teeth"],
["meza", "table"],
["mfalme", "king"],
["mfano", "example"],
["mfumo", "system"],
["mfupa", "bone"],
["mfupi", "short"],
["mgawanyiko", "divide"],
["mgawanyiko", "division"],
["mguu", "foot"],
["mguu", "leg"],
["mia", "hundred"],
["miguu", "feet"],
["milele", "ever"],
["milioni", "million"],
["mimi", "I"],
["mimi", "me"],
["miss ya", "miss"],
["mitaani", "street"],
["mizizi", "root"],
["mji mkuu wa", "capital"],
["mji", "city"],
["mji", "town"],
["mkali", "bright"],
["mkali", "sharp"],
["mkate", "bread"],
["mke", "wife"],
["mkia", "tail"],
["mkondo", "stream"],
["mkono", "arm"],
["mkono", "hand"],
["mlango", "door"],
["mlima", "mount"],
["mlima", "mountain"],
["mnyama", "animal"],
["moja kwa moja", "direct"],
["moja kwa moja", "straight"],
["moja", "one"],
["moja", "single"],
["molekuli", "molecule"],
["moto", "fire"],
["moto", "hot"],
["moyo", "heart"],
["mpaka", "until"],
["mpango", "deal"],
["mpango", "plan"],
["mpira", "ball"],
["mpishi", "cook"],
["mpole", "gentle"],
["mpya", "new"],
["mraba", "square"],
["mrefu", "tall"],
["mrefu", "term"],
["mrengo", "wing"],
["msaada", "help"],
["msaada", "support"],
["msalaba", "cross"],
["mshangao", "surprise"],
["msichana", "girl"],
["msimu", "season"],
["msingi", "base"],
["msingi", "basic"],
["msitu", "forest"],
["mstari", "row"],
["mtazamo", "view"],
["mtihani", "test"],
["mtini", "fig"],
["mto", "river"],
["mtoto", "baby"],
["mtoto", "child"],
["mtu", "man"],
["mtu", "person"],
["mtumwa", "slave"],
["muda mrefu", "long"],
["muhimu", "necessary"],
["muundo", "pattern"],
["muziki", "music"],
["mvua", "rain"],
["mvuke", "steam"],
["mvulana", "boy"],
["mwaka", "year"],
["mwamba", "rock"],
["mwana", "son"],
["mwanafunzi", "student"],
["mwanamke", "lady"],
["mwanamke", "woman"],
["mwanga", "light"],
["mwendo", "motion"],
["mwenyewe", "own"],
["mwezi", "month"],
["mwezi", "moon"],
["mwili", "body"],
["mwingine", "else"],
["mwisho", "end"],
["mwisho", "final"],
["mwisho", "last"],
["mzazi", "parent"],
["mzulia", "invent"],
["mzunguko", "circle"],
["na crease", "crease"],
["na", "and"],
["na", "by"],
["na", "have"],
["nadhani", "guess"],
["naendelea", "kept"],
["nafaka", "corn"],
["nafasi", "chance"],
["nafasi", "position"],
["nafasi", "space"],
["nahodha", "captain"],
["nakala", "copy"],
["nane", "eight"],
["naye", "him"],
["nchi", "country"],
["ndege", "bird"],
["ndege", "plane"],
["ndiyo", "yes"],
["ndogo", "small"],
["ndoto", "dream"],
["ndugu", "brother"],
["neema", "favor"],
["nene", "thick"],
["neno", "word"],
["ngazi ya", "level"],
["ngoma", "dance"],
["ngozi", "skin"],
["ngumu", "hard"],
["nguo", "clothe"],
["nguvu", "force"],
["nguvu", "might"],
["nguvu", "power"],
["nguvu", "strong"],
["ng’ombe", "cow"],
["ni pamoja na", "include"],
["ni", "am"],
["ni", "is"],
["ninaenda zangu", "i am just going home"],
["nini", "what"],
["ninyi", "you"],
["nishati", "energy"],
["nitakuwepo", "I will be there"],
["niwie radhi", "i beg your pardon"],
["njano", "yellow"],
["nje", "out"],
["njia", "method"],
["njia", "path"],
["njia", "way"],
["njoo", "come (command)"],
["nne", "four"],
["nomino", "noun"],
["note", "note"],
["numeral", "numeral"],
["nusu", "half"],
["nyama", "meat"],
["nyasi", "grass"],
["nyekundu", "red"],
["nyembamba", "thin"],
["nyeupe", "white"],
["nyeusi", "black"],
["nyingine", "other"],
["nyota", "star"],
["nyuma ya", "behind"],
["nyuma", "back"],
["nyumba", "house"],
["nyumbani", "home"],
["nywele", "hair"],
["nzito", "heavy"],
["nzuri", "good"],
["ofisi", "office"],
["oh", "oh"],
["oksijeni", "oxygen"],
["orodha", "list"],
["orodha", "roll"],
["osha", "wash"],
["paka", "cat"],
["pamba", "cotton"],
["pamoja", "together"],
["pana", "broad"],
["pana", "wide"],
["pande zote", "round"],
["papo", "instant"],
["pembetatu", "triangle"],
["pete", "ring"],
["pia", "also"],
["pia", "too"],
["picha", "picture"],
["pigo", "blow"],
["pili", "second"],
["polepole", "slow"],
["pori", "wild"],
["pua", "nose"],
["pwani", "coast"],
["pwani", "shore"],
["quotient ya", "quotient"],
["rafiki", "friend"],
["rahisi", "simple"],
["ramani", "map"],
["rangi", "color"],
["rangi", "paint"],
["rekodi", "record"],
["reli", "rail"],
["ridhika", "to be satisfied"],
["saa sita mchana", "noon"],
["saa", "clock"],
["saa", "hour"],
["saba", "seven"],
["sababu", "cause"],
["sababu", "reason"],
["safari", "ride"],
["safari", "trip"],
["safi", "clean"],
["safi", "fresh"],
["safu", "column"],
["sahihi", "correct"],
["sahihi", "proper"],
["sakafu", "floor"],
["salama", "safe"],
["samaki", "fish"],
["sana", "very"],
["sanaa", "art"],
["sanduku", "box"],
["sasa", "current"],
["sasa", "now"],
["sasa", "present"],
["sauti", "sound"],
["sauti", "voice"],
["saw", "saw"],
["sawa", "equal"],
["sawa", "same"],
["sawa", "similar"],
["sayansi", "science"],
["sayari", "planet"],
["search", "search"],
["sehemu", "fraction"],
["sehemu", "part"],
["sehemu", "section"],
["sehemu", "segment"],
["sekta ya", "industry"],
["serikali", "govern"],
["shahada ya", "degree"],
["shairi", "poem"],
["shamba", "farm"],
["shamba", "field"],
["sheria", "law"],
["shida", "trouble"],
["shimo", "hole"],
["shingo", "neck"],
["shule", "school"],
["si", "won’t"],
["sikio", "ear"],
["siku za nyuma", "past"],
["siku", "day"],
["silabi", "syllable"],
["simu", "call"],
["simu", "number"],
["sisi", "us"],
["sisi", "we"],
["sita", "six"],
["soko", "market"],
["somo", "subject"],
["suffix", "suffix"],
["sukari", "sugar"],
["sumaku", "magnet"],
["sura", "shape"],
["suti", "suit"],
["swali", "question"],
["tabasamu", "smile"],
["tabia ya", "character"],
["tafadhali", "please"],
["taifa", "nation"],
["tairi", "tire"],
["tajiri", "rich"],
["takwimu", "figure"],
["tangu", "since"],
["tano", "five"],
["tatizo", "problem"],
["tatu", "third"],
["tatu", "three"],
["tawi", "branch"],
["tayari", "ready"],
["tena", "again"],
["tendo", "act"],
["thamani", "value"],
["theluji", "snow"],
["tie", "tie"],
["timu", "team"],
["tisa", "nine"],
["tofauti", "differ"],
["tofauti", "separate"],
["tone", "tone"],
["treni", "train"],
["tu", "just"],
["tu", "only"],
["tube", "tube"],
["tukio", "event"],
["ua", "flower"],
["uangaze", "shine"],
["udongo", "soil"],
["ufumbuzi", "solution"],
["ufunguo", "key"],
["uhakika", "point"],
["uhakika", "sure"],
["ujumla", "general"],
["ujuzi", "skill"],
["ukubwa", "size"],
["ukurasa", "page"],
["ukuta", "wall"],
["ukweli", "fact"],
["uliofanyika", "held"],
["umati wa watu", "crowd"],
["umeme", "electric"],
["umri wa", "old"],
["umri", "age"],
["unataka", "wish"],
["unaweza", "can"],
["uongo", "lie"],
["up", "up"],
["upande", "side"],
["upande", "turn"],
["upendo", "love"],
["upepo", "wind"],
["urefu", "length"],
["usafiri", "travel"],
["usambazaji", "supply"],
["usijali", "don’t worry"],
["usiku", "night"],
["usingizi", "sleep"],
["uso", "face"],
["uso", "surface"],
["utafiti", "study"],
["utawala", "rule"],
["utulivu", "quiet"],
["uwezo", "able"],
["uzito", "weight"],
["uzoefu", "experience"],
["uzuri", "beauty"],
["vidogo", "tiny"],
["vifaa", "material"],
["vigumu", "difficult"],
["vijana", "young"],
["vita", "war"],
["vizuri", "well"],
["vowel", "vowel"],
["vyenye", "contain"],
["vyombo vya habari", "press"],
["wa pretty", "pretty"],
["wadogo", "scale"],
["wadudu", "insect"],
["wafu", "dead"],
["wakati wa", "during"],
["wakati", "moment"],
["wakati", "time"],
["wakati", "when"],
["wakati", "while"],
["wako", "are"],
["wakuu", "chief"],
["wala", "nor"],
["wale", "those"],
["walikuwa", "were"],
["waliona", "felt"],
["waliopotea", "lost"],
["wanalinganisha", "equate"],
["wanaonekana", "seem"],
["wanataka", "want"],
["wanaume", "men"],
["wanawake", "women"],
["wao", "they"],
["wapenzi", "dear"],
["watoto", "children"],
["watu", "people"],
["waya", "wire"],
["wazi", "clear"],
["wazi", "open"],
["wazi", "plain"],
["wazo", "idea"],
["wazo", "thought"],
["wengi", "many"],
["wengine", "rest"],
["wetu", "our"],
["wiki", "week"],
["wimbi", "wave"],
["wimbo", "song"],
["wingi", "plural"],
["wingu", "cloud"],
["wote wawili", "both"],
["ya lone", "lone"],
["ya mti", "tree"],
["ya", "of"],
["yadi", "yard"],
["yai", "egg"],
["yake", "her"],
["yake", "his"],
["yake", "it"],
["yako", "your"],
["yangu", "mine"],
["yangu", "my"],
["yao", "their"],
["yao", "them"],
["yeye", "he"],
["yeye", "she"],
["yoyote", "any"],
["za Redio", "radio"],
["zaidi", "more"],
["zaidi", "most"],
["ziara", "visit"],
["zima", "whole"],
["zinahitaji", "require"],
["zinaonyesha", "indicate"],
["ziwa", "lake"],
["zoezi", "exercise"],
];
